### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by sondr3** [inf112-v20/biblioteket#20]
High level goals for this sprint:

- Getting a good representation for the board
- Good, proper, abstractions for robots and movement
- Find some nice graphical elements

Implementation:

- [x] A board representation (#22)
  - [x] Locations for objects
- [ ] A player that has control over robot(s) (#23)
  - [x] A robot class
- [ ] A map reader that reads from the `.tmx` files and converts it to a board (#21)
- [ ] A simple interface (#24)
- [x] Some testing for behaviour (#26)
- [x] `GameObjects` (or some name thereof) (#25)

Documentation:

- [ ] Write user stories etc
